// cmd_name,  id, is_jump, ...
DEF_CMD(halt, 0,  false, {halt();})
DEF_CMD(add,  1,  false, {add(&proc->stack);})
DEF_CMD(sub,  2,  false, {sub(&proc->stack);})
DEF_CMD(mul,  3,  false, {mul(&proc->stack);})
DEF_CMD(div,  4,  false, {div(&proc->stack);})
DEF_CMD(push, 5,  false, {})
DEF_CMD(pop,  6,  false, {})
DEF_CMD(in,   7,  false, {in(&proc->stack);})
DEF_CMD(out,  8,  false, {out(&proc->stack);})
DEF_CMD(jmp,  16, true,  {})
DEF_CMD(je,   17, true,  {})
DEF_CMD(jne,  18, true,  {})
DEF_CMD(ja,   19, true,  {})
DEF_CMD(jea,  20, true,  {})
DEF_CMD(jb,   21, true,  {})
DEF_CMD(jeb,  22, true,  {})